package vista;

import java.io.IOException;
import java.util.Collections;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Utilities;

/**
 *
 * @author Fabian Esteban Lopez Arias
 */
public class UICliente extends javax.swing.JFrame {

    /**
     * Creates new form UICliente
     */
    LinkedList<Cliente> listaClientes;

    public UICliente() {
        listaClientes = new LinkedList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        AgregarButton = new javax.swing.JButton();
        CancelarButton = new javax.swing.JButton();
        MostrarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaMostrar = new javax.swing.JTextArea();
        SaveButton = new javax.swing.JButton();
        LoadDataButton = new javax.swing.JButton();
        IndexText = new javax.swing.JTextField();
        IndexOfButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AddFirstButton = new javax.swing.JCheckBoxMenuItem();
        AddLastButton = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        InvertListButton = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jLabel1.setText("Datos Cliente");

        jTextField1.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jTextField1.setText("Nombre Cliente");

        jTextField2.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jTextField2.setText("Telefono Cliente");

        jTextField3.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jTextField3.setText("Correo Cliente");

        jTextField4.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jTextField4.setText("Código Cliente");

        jTextField5.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jTextField5.setText("Edad Cliente");

        AgregarButton.setText("Agregar");
        AgregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarButtonActionPerformed(evt);
            }
        });

        CancelarButton.setText("Cancelar");
        CancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarButtonActionPerformed(evt);
            }
        });

        MostrarButton.setText("Mostrar");
        MostrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarButtonActionPerformed(evt);
            }
        });

        TextAreaMostrar.setEditable(false);
        TextAreaMostrar.setColumns(20);
        TextAreaMostrar.setRows(5);
        jScrollPane1.setViewportView(TextAreaMostrar);

        SaveButton.setText("Guardar");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        LoadDataButton.setText("Cargar");
        LoadDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadDataButtonActionPerformed(evt);
            }
        });

        IndexText.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        IndexText.setText("digite nombre");
        IndexText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndexTextActionPerformed(evt);
            }
        });

        IndexOfButton.setText("IndexOf");
        IndexOfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndexOfButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        AddFirstButton.setSelected(true);
        AddFirstButton.setText("AddFirst");
        AddFirstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFirstButtonActionPerformed(evt);
            }
        });
        jMenu1.add(AddFirstButton);

        AddLastButton.setSelected(true);
        AddLastButton.setText("AddLast");
        AddLastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLastButtonActionPerformed(evt);
            }
        });
        jMenu1.add(AddLastButton);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Remove");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Clear");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem2);

        InvertListButton.setText("InvertList");
        InvertListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvertListButtonActionPerformed(evt);
            }
        });
        jMenu1.add(InvertListButton);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IndexOfButton)
                                .addGap(18, 18, 18)
                                .addComponent(IndexText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CancelarButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(AgregarButton)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(MostrarButton)
                        .addGap(120, 120, 120))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LoadDataButton)
                                .addGap(6, 6, 6))
                            .addComponent(SaveButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MostrarButton)
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CancelarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AgregarButton)
                        .addGap(18, 18, 18)
                        .addComponent(SaveButton)
                        .addGap(18, 18, 18)
                        .addComponent(LoadDataButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IndexOfButton)
                            .addComponent(IndexText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarButtonActionPerformed

        String nombreCliente = jTextField1.getText();
        String telefonoCliente = jTextField2.getText();
        String correoCliente = jTextField3.getText();
        String codigoCliente = jTextField4.getText();
        int edadCliente = Integer.parseInt(jTextField5.getText());

        Cliente objCliente = new Cliente(codigoCliente, edadCliente, nombreCliente, telefonoCliente, correoCliente);
        listaClientes.add(objCliente);
        System.out.println(listaClientes);


    }//GEN-LAST:event_AgregarButtonActionPerformed

    private void CancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CancelarButtonActionPerformed

    private void MostrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarButtonActionPerformed
        String mostrar = "";
        for (Cliente elem : listaClientes) {
            mostrar += elem.toString();
        }
        TextAreaMostrar.setText(mostrar);

    }//GEN-LAST:event_MostrarButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        try {
            boolean t = Utilities.saveFile(listaClientes);
            if (t) {
                JOptionPane.showMessageDialog(null, "Si se guardo el archivo en la raiz");
            } else {
                JOptionPane.showMessageDialog(null, "No");
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void LoadDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadDataButtonActionPerformed
        try {
            listaClientes = Utilities.readFile();
            JOptionPane.showMessageDialog(null, "Si se cargo el archivo.");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_LoadDataButtonActionPerformed

    private void AddFirstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFirstButtonActionPerformed
        // TODO add your handling code here:
        String nombreCliente = jTextField1.getText();
        String telefonoCliente = jTextField2.getText();
        String correoCliente = jTextField3.getText();
        String codigoCliente = jTextField4.getText();
        int edadCliente = Integer.parseInt(jTextField5.getText());

        Cliente objCliente = new Cliente(codigoCliente, edadCliente, nombreCliente, telefonoCliente, correoCliente);

        listaClientes.addFirst(objCliente);
        System.out.println(listaClientes);
    }//GEN-LAST:event_AddFirstButtonActionPerformed

    private void AddLastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLastButtonActionPerformed
        String nombreCliente = jTextField1.getText();
        String telefonoCliente = jTextField2.getText();
        String correoCliente = jTextField3.getText();
        String codigoCliente = jTextField4.getText();
        int edadCliente = Integer.parseInt(jTextField5.getText());

        Cliente objCliente = new Cliente(codigoCliente, edadCliente, nombreCliente, telefonoCliente, correoCliente);

        listaClientes.addLast(objCliente);
        System.out.println(listaClientes);
    }//GEN-LAST:event_AddLastButtonActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        listaClientes.remove();
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        listaClientes.clear();
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void IndexTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndexTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IndexTextActionPerformed

    private void IndexOfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndexOfButtonActionPerformed

        int aux = 0;
        aux = listaClientes.element().getNombreP().indexOf(IndexText.getText());

        if (aux != -1) {
            TextAreaMostrar.setText("El índice del cliente en la lista es: " + aux);
        } else {
            TextAreaMostrar.setText("Cliente digitado `" + IndexText.getText() + "` no encontrado en la lista.");
        }

        System.out.println(listaClientes);
    }//GEN-LAST:event_IndexOfButtonActionPerformed

    private void InvertListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvertListButtonActionPerformed
        LinkedList<Cliente> reversedList = new LinkedList<>(listaClientes);
        Collections.reverse(reversedList);
        
    }//GEN-LAST:event_InvertListButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UICliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UICliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UICliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UICliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UICliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem AddFirstButton;
    private javax.swing.JCheckBoxMenuItem AddLastButton;
    private javax.swing.JButton AgregarButton;
    private javax.swing.JButton CancelarButton;
    private javax.swing.JButton IndexOfButton;
    private javax.swing.JTextField IndexText;
    private javax.swing.JMenuItem InvertListButton;
    private javax.swing.JButton LoadDataButton;
    private javax.swing.JButton MostrarButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextArea TextAreaMostrar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
